version: '3'

services:
  app:
    env_file:
      - ../.env.dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspaces/rails_vulnerability_trial:cached
      - bundle-volume:/workspaces/rails_vulnerability_trial/.bundle

    command: sleep infinity

    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
      - ../.env.dev
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql

volumes:
  db-store:
  bundle-volume:
